name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore src/Chirp.Web/Chirp.Web.csproj
    - name: Build
      run: dotnet build src/Chirp.Web/Chirp.Web.csproj --no-restore
    - name: Test
      run: dotnet test src/Chirp.Web/Chirp.Web.csproj --no-build --verbosity normal
      run: dotnet test test/Chirp.DB.Tests --no-build --verbosity normal
